#!/bin/sh

IF=$1
STATUS=$2
LOG_FILE="$HOME/dispatcher.log"
OUTPUT_FILE="$HOME/latlon.txt"
# Create files if not already created.
touch $LOG_FILE
touch $OUTPUT_FILE

echo "Script started at $(date)" >> $LOG_FILE
echo "Interface: $IF, Status: $STATUS" >> $LOG_FILE

if [ "$STATUS" = "up" ]; then
    sudo tzupdate
    echo "tzupdate command executed" >> $LOG_FILE

    # Call the geolocation API and capture the output
    LATLON=`curl -s https://ipinfo.io/loc`
    echo "Latitude and Longitude: $LATLON" >> $LOG_FILE

    LAT=$(echo $LATLON | cut -d ',' -f 1)
    LON=$(echo $LATLON | cut -d ',' -f 2)

    echo "$LAT,$LON" > $OUTPUT_FILE
    echo "Latitude: $LAT, Longitude: $LON" >> $LOG_FILE

    killall xflux;
    echo "xflux killed" >> $LOG_FILE

    while true;
        do allxflux=$(pidof xflux);
        wtsp=" ";
        tmpxflux=${allxflux%%"$wtsp"*};
        allxflux=${allxflux#*"$wtsp"};
        case "$allxflux" in
            *" "*)
                kill -9 "$tmpxflux";
                continue;
            ;;
            *)
                kill -9 "$tmpxflux";
                break;
            ;;
        esac;
    done;
    env >> $LOG_FILE
    echo "New xflux started" >> $LOG_FILE
    xflux -l $LAT -g $LON -k 2000 &

    # Record the end of the script in the log file
    echo "Script finished at $(date)" >> $LOG_FILE

