#!/bin/bash

username=$(who | awk '{print $1; exit}')

OUTPUT_FILE="/home/$username/latlon.txt"

# Test if output file exists
if [ -f "$OUTPUT_FILE" ]; then

    LAT=$(cat $OUTPUT_FILE | cut -d ',' -f 1)
    LON=$(cat $OUTPUT_FILE | cut -d ',' -f 2)

    export XAUTHORITY=/home/$username/.Xauthority
    export DISPLAY=:0

    kill_xflux() {
   	killall xflux
	while true;
        	do allxflux=$(pidof xflux);
        	wtsp=" ";
        	tmpxflux=${allxflux%%"$wtsp"*};
        	allxflux=${allxflux#*"$wtsp"};
        	case "$allxflux" in
                	*" "*)
                        	kill -9 "$tmpxflux";
                        	continue;
                	;;
                	*)
                        	kill -9 "$tmpxflux";
                        	break;
                	;;
        	esac;
	done;
    }

    kill_xflux

    xflux -l $LAT -g $LON -k 2000 >/dev/null 2>&1 &

else
    echo "Output file $OUTPUT_FILE does not exist."
    exit 1
fi

